version = 0.1

[default.deploy.paramters]

stack_name = "myapp-prod"
s3_bucket = "myapp-prod-artifcats-12345"
s3_prefix = "myapp-prod"
region = "ap-south-1"
parameter_overrides = "EnvironmentName=staging ProjectName=myapp CorsOrigin='*' BurstLimit=500 RateLimit=250 ProvisionedConcurrency=10"
capabilities = "CAPABLITY_IAM CAPABILITY_NAMED_IAM"
confirm_changeset = "true"

